program IBStore;

uses
  Forms,
  TPrevInst,
  Main in 'Main.pas' {MainForm},
  StoreDM in 'StoreDM.pas' {StoreDataModule: TDataModule},
  About in 'About.pas' {AboutBox},
  Login in 'Login.pas' {LoginForm},
  Customer in 'Customer.pas' {CustomerForm},
  CustomerItem in 'CustomerItem.pas' {CustomerItemForm},
  Product in 'Product.pas' {ProductForm},
  ProductItem in 'ProductItem.pas' {ProductItemForm},
  CategoryItem in 'CategoryItem.pas' {CategoryItemForm},
  Category in 'Category.pas' {CategoryForm},
  BuyOrder in 'BuyOrder.pas' {BuyOrderForm},
  BuyOrderItem in 'BuyOrderItem.pas' {BuyOrderItemForm},
  BuyStructure in 'BuyStructure.pas' {BuyStructureForm},
  Store in 'Store.pas' {StoreForm},
  SaleOrder in 'SaleOrder.pas' {SaleOrderForm},
  SaleOrderItem in 'SaleOrderItem.pas' {SaleOrderItemForm},
  DivisionItem in 'DivisionItem.pas' {DivisionItemForm},
  Options in 'Options.pas' {OptionsForm},
  SaleStructure in 'SaleStructure.pas' {SaleStructureForm},
  ProductSelect in 'ProductSelect.pas' {ProductSelectForm},
  BuyStoreSelect in 'BuyStoreSelect.pas' {BuyStoreSelectForm},
  PaymentCash in 'PaymentCash.pas' {PaymentCashForm},
  PaymentCashItem in 'PaymentCashItem.pas' {PaymentCashItemForm},
  CustomerSelect in 'CustomerSelect.pas' {CustomerSelectForm},
  PayOrderSelect in 'PayOrderSelect.pas' {PayOrderSelectForm},
  FirmSelect in 'FirmSelect.pas' {FirmSelectForm},
  HomeOrder in 'HomeOrder.pas' {HomeOrderForm},
  HomeOrderItem in 'HomeOrderItem.pas' {HomeOrderItemForm},
  DivisionSelect in 'DivisionSelect.pas' {DivisionSelectForm},
  Bank in 'Bank.pas' {BankForm},
  BankItem in 'BankItem.pas' {BankItemForm},
  VAT in 'VAT.pas' {VATForm},
  VATItem in 'VATItem.pas' {VATItemForm},
  ProductDescription in 'ProductDescription.pas' {ProductDescriptionForm},
  BuyStoreItem in 'BuyStoreItem.pas' {BuyStoreItemForm},
  Measure in 'Measure.pas' {MeasureForm},
  MeasureItem in 'MeasureItem.pas' {MeasureItemForm},
  Producer in 'Producer.pas' {ProducerForm},
  ProducerItem in 'ProducerItem.pas' {ProducerItemForm},
  CountryItem in 'CountryItem.pas' {CountryItemForm},
  Country in 'Country.pas' {CountryForm},
  CCD in 'CCD.pas' {CCDForm},
  CCDItem in 'CCDItem.pas' {CCDItemForm},
  Certificate in 'Certificate.pas' {CertificateForm},
  CertificateItem in 'CertificateItem.pas' {CertificateItemForm},
  PaymentOrder in 'PaymentOrder.pas' {PaymentOrderForm},
  PaymentOrderItem in 'PaymentOrderItem.pas' {PaymentOrderItemForm},
  Firm in 'Firm.pas' {FirmForm},
  FirmItem in 'FirmItem.pas' {FirmItemForm},
  BuyPriceItem in 'BuyPriceItem.pas' {BuyPriceItemForm},
  TypePrice in 'TypePrice.pas' {TypePriceForm},
  TypePriceItem in 'TypePriceItem.pas' {TypePriceItemForm},
  PaymentBank in 'PaymentBank.pas' {PaymentBankForm},
  PaymentBankItem in 'PaymentBankItem.pas' {PaymentBankItemForm},
  StoreSelect in 'StoreSelect.pas' {StoreSelectForm},
  HomeStructure in 'HomeStructure.pas' {HomeStructureForm},
  HomeStoreSelect in 'HomeStoreSelect.pas' {HomeStoreSelectForm},
  StoreItem in 'StoreItem.pas' {StoreItemForm},
  HomeStoreItem in 'HomeStoreItem.pas' {HomeStoreItemForm},
  PrintOrder in 'PrintOrder.pas' {PrintOrderForm},
  HomeProperSelect in 'HomeProperSelect.pas' {HomeProperSelectForm},
  SaleProperSelect in 'SaleProperSelect.pas' {SaleProperSelectForm},
  ReportDM in 'ReportDM.pas' {ReportDataModule: TDataModule},
  ReportPriceList in 'ReportPriceList.pas' {ReportPriceListForm},
  ReportPrice in 'ReportPrice.pas' {ReportPriceForm},
  Group in 'Group.pas' {GroupForm},
  GroupItem in 'GroupItem.pas' {GroupItemForm},
  ReportOrderSelect in 'ReportOrderSelect.pas' {ReportOrderSelectForm},
  VATRate in 'VATRate.pas' {VATRateForm},
  HomeTypeSelect in 'HomeTypeSelect.pas' {HomeTypeSelectForm},
  Registration in 'Registration.pas' {RegistrationForm},
  ReportDebtor in 'ReportDebtor.pas' {ReportDebtorForm},
  ReportDebtorPrint in 'ReportDebtorPrint.pas' {ReportDebtorPrintForm},
  ReportDebtorSelect in 'ReportDebtorSelect.pas' {ReportDebtorSelectForm},
  ReportCashBook in 'ReportCashBook.pas' {ReportCashBookForm},
  ReportCashBookItem in 'ReportCashBookItem.pas' {ReportCashBookItemForm},
  ReportCashBookDateSelect in 'ReportCashBookDateSelect.pas' {ReportCashBookDateSelectForm},
  InitialBalance in 'InitialBalance.pas' {InitialBalanceForm},
  InitialBalanceItem in 'InitialBalanceItem.pas' {InitialBalanceItemForm},
  InitialRemains in 'InitialRemains.pas' {InitialRemainsForm},
  ReportCirculate in 'ReportCirculate.pas' {ReportCirculateForm},
  ReportCirculateSelect in 'ReportCirculateSelect.pas' {ReportCirculateSelectForm},
  ReportRemains in 'ReportRemains.pas' {ReportRemainsForm},
  ReportCommodityMoney in 'ReportCommodityMoney.pas' {ReportCommodityMoneyForm},
  ReportRevise in 'ReportRevise.pas' {ReportReviseForm},
  IntervalSelect in 'IntervalSelect.pas' {IntervalSelectForm},
  FirstAid in 'FirstAid.pas' {FirstAidForm},
  ssdefines in 'ssdefines.pas',
  SQLMonitorForm in 'SQLMonitorForm.pas' {SQLMonitor};

{$R *.res}

begin
  if InitInstance then
  begin // Запуск программы
    Application.Initialize;
    Application.Title := 'Storehouse Enterprise';
    Application.CreateForm(TStoreDataModule, StoreDataModule);
  Application.CreateForm(TMainForm, MainForm);
  Application.CreateForm(TReportDataModule, ReportDataModule);
  Application.Run;
  end;
end.
